"""email  and phone unique with user_id

Revision ID: 31f96756bad4
Revises: 0cea830cb8b5
Create Date: 2025-09-12 20:16:01.509918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f96756bad4'
down_revision: Union[str, Sequence[str], None] = '0cea830cb8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('contacts_email_key'), 'contacts', type_='unique')
    op.drop_constraint(op.f('contacts_phone_number_key'), 'contacts', type_='unique')
    op.create_unique_constraint('uq_user_contact_email', 'contacts', ['user_id', 'email'])
    op.create_unique_constraint('uq_user_contact_phone', 'contacts', ['user_id', 'phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_contact_phone', 'contacts', type_='unique')
    op.drop_constraint('uq_user_contact_email', 'contacts', type_='unique')
    op.create_unique_constraint(op.f('contacts_phone_number_key'), 'contacts', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('contacts_email_key'), 'contacts', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
